name: PHP CS Fixer  # Vérifie le style de code PHP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  phpcsfixer:
    runs-on: ubuntu-latest  # Machine virtuelle Ubuntu GitHub Actions

    steps:
      - uses: actions/checkout@v4       # Récupère ton code

      - uses: shivammathur/setup-php@v2 # Installe PHP
        with:
          php-version: '8.4'            # Même version pour rester cohérent
          
      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest
        # Installe toutes les dépendances (dont php-cs-fixer)

      - name: Run PHP CS Fixer (dry-run)
        run: ./vendor/bin/php-cs-fixer fix --diff --dry-run --verbose
        # Vérifie le style sans le modifier
        # Si le style est incorrect -> le job échoue (croix rouge)



