name: PHPStan analysis  # Analyse statique du code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  phpstan:
    runs-on: ubuntu-latest  # Machine virtuelle Ubuntu sur GitHub

    steps:
      - uses: actions/checkout@v4       # Clone le dépôt dans l'environnement CI

      - uses: shivammathur/setup-php@v2 # Installe PHP dans l'environnement CI
        with:
          php-version: '8.4'            # On garde la même version de PHP que dans phpunit.yml

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest
        # Récupère vendor/ pour que phpstan soit dispo

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --no-progress
        # Analyse statique du code selon phpstan.neon


