name: PHPUnit tests  # Nom du workflow tel qu'il apparaîtra dans GitHub Actions

on:
  push:              # Déclenché à chaque push
    branches: [ "main" ]  # seulement sur la branche main
  pull_request:      # Déclenché aussi sur les Pull Requests vers main
    branches: [ "main" ]

jobs:
  phpunit:                 # Nom du job
    runs-on: ubuntu-latest # Machine virtuelle Ubuntu fournie par GitHub

    steps:
      - uses: actions/checkout@v4        # Récupère le code du repo dans la machine CI

      - uses: shivammathur/setup-php@v2  # Installe PHP dans la machine CI
        with:
          php-version: '8.4'             # IMPORTANT : version PHP >= 8.3 car PHPUnit 12 l'exige
          coverage: none                 # On ne génère pas de rapport de couverture

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest
        # Installe les dépendances dev (phpunit, phpstan, php-cs-fixer...) à partir du composer.lock

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
        # Lance les tests unitaires



